smashedavo/backend/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "backend"
urlpatterns = [
    # path('users/', views.users, name='users'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup_user, name='signup'),
    path('check_username_exists/<username>', views.check_username_exists, name='check_username_exists'),
    path('blogposts/', views.blogposts, name='blogposts'),
    path('expenses/', views.expenses, name='expenses'),
    path('expenses/create/', views.expenses_create, name='expenses_create'),
    path('expenses/<int:expense_id>/', views.expenses_select, name='expenses_select'),
    path('expenses/<int:expense_id>/edit/', views.expenses_edit, name='expenses_edit'),
    path('expenses/<int:expense_id>/delete/', views.expenses_delete, name='expenses_delete'),
    path('regularpayments/', views.regularpayments, name='regularpayments'),
    path('regularpayments/create/', views.regularpayments_create, name='regularpayments_create'),
    path('regularpayments/<int:regularpayment_id>/', views.regularpayments_select, name='regularpayments_select'),
    path('regularpayments/<int:regularpayment_id>/edit/', views.regularpayments_edit, name='regularpayments_edit'),
    # path('expense_category_choices/', views.expense_category_choices, name='expense_category_choices'),
]

smashedavo/mortgage/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "mortgage"
urlpatterns = [
    # path('', views.index, name="index"),
    # path('login/', views.user_login, name='login'),
    # path('signup/', views.user_signup, name='signup'),
    # path('logout/', views.user_logout, name='logout'),
    # path('blog/', BlogPostListView.as_view(), name='blog_list'),
    # path('blog/create', views.blog_create, name='blog_create'),
    # path('blog/<int:blogpost_id>/delete', views.blog_delete, name='blog_delete'),
    # path('blog/<int:blogpost_id>/edit', views.blog_edit, name='blog_edit'),
    # path('blog/<int:pk>/', BlogPostDetailView.as_view(), name='blog_detail'),
    # path('create/', views.create, name='create'),
    # path('for_approval/<error>', views.for_approval, name='for_approval'),
    # # path('for_approval/', views.for_approval_with_error, name='for_approval_with_error'),
    # path('generate_transactions/', views.generate_transactions, name='generate_transactions'),
    # path('loans/', LoanListView.as_view(), name='loan_list'),
    # path('loans/create/', views.loan_create, name='loan_create'),
    # path('loans/<int:loan_id>/payment', views.loan_payment, name='loan_payment'),
    # # path('loans/<int:loan_id>/detail', views.loan_detail, name='loan_detail'),
    # path('loans/<int:loan_id>/delete', views.loan_delete, name='loan_delete'),
    # path('loans/<int:loan_id>/edit', views.loan_edit, name='loan_edit'),
    # path('expenseinterval/', ExpenseIntervalListView.as_view(), name='expenseinterval_list'),
    # path('expenseinterval/create/', views.expenseinterval_create, name='expenseinterval_create'),
    # path('expenseinterval/<int:expenseinterval_id>/details', views.expenseinterval_details, name='expenseinterval_details'),
    # path('expenseinterval/<int:expenseinterval_id>/delete', views.expenseinterval_delete, name='expenseinterval_delete'),
    # path('expenseinterval/<int:expenseinterval_id>/edit', views.expenseinterval_edit, name='expenseinterval_edit'),
    # path('expenseadhoc/', ExpenseAdhocListView.as_view(), name='expenseadhoc_list'),
    # path('expenseadhoc/create/', views.expenseadhoc_create, name='expenseadhoc_create'),
    # # path('expenseadhoc/approve_all', views.expenseadhoc_approve_all, name='expenseadhoc_approve_all'),
    # path('expenseadhoc/<int:expenseadhoc_id>/approve', views.expenseadhoc_approve, name='expenseadhoc_approve'),
    # path('expenseadhoc/<int:expenseadhoc_id>/delete', views.expenseadhoc_delete, name='expenseadhoc_delete'),
    # path('expenseadhoc/<int:expenseadhoc_id>/edit', views.expenseadhoc_edit, name='expenseadhoc_edit'),
    # path('backend_get_all_blogposts/', views.backend_get_all_blogposts, name='backend_get_all_blogposts'),
]

smashedavo/smashedavo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include("backend.urls")),
    path('mortgage/', include("mortgage.urls")),
]

smashedavo/backend/forms.py
from django import forms
from .models import *

class ExpenseForm(forms.ModelForm):
    '''Form for creating a new instance of the EventInterval model.
    '''
    class Meta:
        model = Expense
        # fields = ['description', 'amount', 'category', 'date', 'approved']
        fields = "__all__"


class RegularPaymentForm(forms.ModelForm):
    '''Form for creating a new instance of the model.
    '''
    class Meta:
        model = RegularPayment
        # fields = ['description', 'amount', 'category', 'interval', 'first_payment_date', 'next_payment_date', 'loan']
        fields = "__all__"

smashedavo/backend/views.py
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.template import loader
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import requires_csrf_token, csrf_exempt
from django.db import IntegrityError
from django.db.models.constraints import UniqueConstraint
from django.forms.models import model_to_dict
from .models import *
from .forms import *
import json
from datetime import date

# TODO - filter objects by current user, currently retrieves all expenses.
# this will require a group or permissions set up, I expect.
# For now, just hardcode the username.

# TODO - restrict retrieved objects to associated user.
# TODO - restrict access to objects not belonging to user.

# TODO - need to restrict object access based on username/permissions.

# TODO - improve consistency of docstrings.

# TODO - improve consistency of single vs double quotes. Consult PEP for guidance.



@csrf_exempt
def login_user(request):
    """TODO - not authenticating anyone but initial superuser.
    """
    
    # get username and password from request.body JSON
    data = json.loads(request.body)
    username = data['username']
    password = data['password']

    # check if provide credential can be authenticated
    user = authenticate(username=username, password=password)

    # if valid user, login user, otherwise return basic data
    if user is not None:
        login(request, user)
        data = {"username": username, "status": "Authenticated"}
    else:
        data = {"username": username, "status": "Unauthenticated"}
    return JsonResponse(data)

@csrf_exempt
def logout_user(request):
    try:
        logout(request)
        return JsonResponse({"status": "Logged Out"})
    except Exception as err:
        return JsonResponse({"status": err})


@csrf_exempt
def signup_user(request):
    '''Attempt to create a new user based on submission of user form.
    '''
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data['username']
        password = data['password']
        first_name = data['first_name']
        last_name = data['last_name']
        if CustomUser.objects.filter(username=username).exists():
            return JsonResponse({"status": "Username already exists"})
        else:
            CustomUser.objects.create_user(username, first_name, last_name, password)
            return JsonResponse({"status": "User created"})


def check_username_exists(request, username):
    if CustomUser.objects.filter(username=username).exists():
        return JsonResponse({"status": "Username already exists"})
    else:
        return JsonResponse({"status": "Username available"})


def blogposts(request):
    json_serializer = serializers.serialize(
        'json',
        BlogPost.objects.all(),
        use_natural_foreign_keys=True,
    )
    return HttpResponse(json_serializer, content_type='application/json')


def expenses(request):
    """
    Retrieves a JSON serialized list of all expenses associated with the currently logged-in user,
    ordered by date in descending order. The serialized data is returned as an HTTP response with
    a content type of 'application/json'.

    Parameters:
    - request (HttpRequest): The HTTP request object containing information about the request.

    Returns:
    - HttpResponse: An HTTP response containing the serialized expense data in JSON format.

    TODO update docstring for consistency with others in code.
    TODO restrict expenses retrieved to those belonging to this user.
    TODO sorts order of objects based on query, now deprecated, will sort directly in frontend instead
    """
    if request.method == 'GET':
        json_serializer = serializers.serialize('json', Expense.objects.all().order_by('-date'), use_natural_foreign_keys=True)
        return HttpResponse(json_serializer, content_type='application/json')

    return JsonResponse({"success": False, "errors": "Method not allowed"})


@csrf_exempt
def expenses_select(request, expense_id):
    """Select specific expense object.

    GET request:
        Return expense object, and expense categories, as JSON.

    TODO - restrict access to only expenses belonging to this user.
    """
    if request.method == 'GET':
        # try to get the object with matching id
        try:
            expense = Expense.objects.get(id=expense_id)
        except Exception as err:
            return JsonResponse({"success": False, "errors": "Expense not found"})

        # TODO somewhat unusual approach to get just one object, try to improve later.
        json_serializer = serializers.serialize('json', [expense], use_natural_foreign_keys=True,)[1:-1]
        json_dict = json.loads(json_serializer)

        # set dictionary of choices for regular payments and loans
        choices_regularpayment = {'None': 'None'}
        for regularpayment in RegularPayment.objects.all():
            choices_regularpayment[regularpayment.description] = regularpayment.description
        choices_loan = {'None': 'None'}
        for loan in Loan.objects.all():
            choices_loan[loan.description] = loan.description
        
        # set additional dictionaries containing choices for select boxes
        json_dict['choices_category'] = dict(Expense.EXPENSE_CHOICES)
        json_dict['choices_regularpayment'] = choices_regularpayment
        json_dict['choices_loan'] = choices_loan

        # return the serialized object
        json_to_return = json.dumps(json_dict)
        return HttpResponse(json_to_return, content_type='application/json')
    
    return JsonResponse({"success": False, "errors": "Invalid request method"})


def expense_form_processing(form_data):
        '''Process raw form data submitted from frontend to create a valid Expense object.
        '''
        # initialise dictionary of processed form data
        form_data_processed = {
            'description': form_data['description'],
            'amount': float(form_data['amount']),
            'category': form_data['category'],
            'date': form_data['date'],  
        }

        # convert html checkbox state to Python Boolean
        if form_data.get('approved') is not None:
            if form_data['approved'] == 'on' or form_data['approved'] == 'true' or form_data['approved'] == 'True':
                form_data_processed['approved'] = True
            else:
                form_data_processed['approved'] = False
        else:
            form_data_processed['approved'] = False

        # get regular payment object if one selected in form
        if form_data['regularpayment'] == 'None':
            form_data_processed['regularpayment'] = None
        else:
            form_data_processed['regularpayment'] = RegularPayment.objects.get(description=form_data['regularpayment'])
        
        # get loan object if one selected in form
        if form_data['loan'] == 'None':
            form_data_processed['loan'] = None
        else:
            form_data_processed['loan'] = Loan.objects.get(description=form_data['loan'])

        # TODO - set user manually for now, automate later
        # user = CustomUser.objects.get(username='colin.c.simpson@gmail.com')
        form_data_processed['user'] = CustomUser.objects.get(username='colin.c.simpson@gmail.com')
        
        return form_data_processed


@csrf_exempt
def expenses_create(request):
    """Create a new expense object, through form submission.

    GET request method:
        Return a Http response containing form fields and expense categories as JSON.

    POST request method:
        Attempt to create a new expense object based on form submitted. 

    TODO - remove hardcoding of username.
    """
    if request.method == 'POST':

        # get raw form data and process to work with backend
        form_data = json.loads(request.body)
        form_data_processed = expense_form_processing(form_data)

        # try except block to get form object and set foreign keys
        try:
            form = ExpenseForm(form_data_processed)
            form.user = form_data_processed['user']
            form.regularpayment = form_data_processed['regularpayment']
            form.loan = form_data_processed['loan']
        except Exception as err:
            return JsonResponse({"success": False, 'errors': 'unknown error in submitting form'})
        
        # create new expense if form is valid, otherwise return error
        if form.is_valid():
            try:
                form.save()
                return JsonResponse({"success": True})
            except Exception as err:
                print('something went wrong with save', err)
                return JsonResponse({"success": False, 'errors': str(err)})
        else:
            print('form not valid', form.errors)
            return JsonResponse({"success": False, 'errors': form.errors})
    
    elif request.method == 'GET':

        # set dictionary of choices for regular payments and loans
        choices_regularpayment = {'None': 'None'}
        for regularpayment in RegularPayment.objects.all():
            choices_regularpayment[regularpayment.description] = regularpayment.description
        choices_loan = {'None': 'None'}
        for loan in Loan.objects.all():
            choices_loan[loan.description] = loan.description
        
        # create JSON response
        json_serializer = json.dumps({
            'pk': None,
            'fields': {
                'description': None,
                'amount': None,
                'category': 'Food',
                'date': str(date.today()),
                'approved': 'on',
                'regularpayment': 'None',
                'loan': 'None',
            },

smashedavo/backend/templates/mortgage/base.html
<!DOCTYPE html>
<html lang="EN">
    <head>
        <meta charset="UTF-8">
        {% load static %}
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% block headerextra %}
        {% endblock headerextra %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <a class="navbar-brand" href="{% url 'mortgage:index' %}">Smashed Avacados</a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mortgage:blog_list' %}">
                                Blog
                            </a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'mortgage:logout' %}">Logout ({{request.user.username}})</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'mortgage:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'mortgage:signup' %}">Signup</a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">

                {% if request.user.is_authenticated %}
                <div class="col-2 bd-sidebar">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mortgage:create' %}">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mortgage:for_approval' False %}">For Approval</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mortgage:loan_list' %}">Loans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'mortgage:expenseinterval_list' %}">Expenses (Interval)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mortgage:expenseadhoc_list' %}">Expenses (Ad hoc)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Incomes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Expenses</a>
                        </li>
                    </ul>
                </div>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <div class="col-10">
                {% else %}
                    <div class="col-12">
                {% endif %}
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>

smashedavo/backend/templates/mortgage/blogpost_delete.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Delete Blog Post</h1>
  
  <div class="alert alert-danger">
    <p>Are you sure you want to delete the following post?</p>
    <h1>{{blogpost.title}}</h1>
    <p>{{blogpost.text}}</p>
  </div>
  <div>
    <form action="{% url 'mortgage:blog_delete' blogpost.id %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-outline-danger" type="submit">Delete</button>
    </form>
  </div>
  <br>
  <div>
    <form action="{% url 'mortgage:blog_list' %}" method="GET">
      <button class="btn btn-outline-secondary" type="submit">Back</button>
    </form>
  </div>

{% endblock content %}

smashedavo/backend/templates/mortgage/blogpost_detail.html
{% extends 'mortgage/base.html' %}

{% block content %}
    <div class="container-fluid">
        <h1>{{blogpost.title}}</h1>
        <p>{{blogpost.text}}</p>
        <p>Published by {{blogpost.user}} on {{blogpost.pub_date}}</p>

        <form action="{% url 'mortgage:blog_list' %}" method="GET">
            <button class="btn btn-outline-secondary" type="submit">Back</button>
        </form>
    </div>

{% endblock content %}

smashedavo/backend/templates/mortgage/blogpost_edit.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Update Blog Post</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-primary" type="submit">Update</button>
  </form>
  <br>
  <div>
    <form action="{% url 'mortgage:blog_list' %}" method="GET">
      <button class="btn btn-outline-secondary" type="submit">Back</button>
    </form>
  </div>

{% endblock content %}

smashedavo/backend/templates/mortgage/contact.html
{% extends 'mortgage/base.html' %}
{% block content %}

<h1>Contact Us</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">SEND MESSAGE</button>
</form>

{% endblock content %}

smashedavo/backend/templates/mortgage/create.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Create New</h1>

  <div class="row">

    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Loan</h5>
          <p class="card-text">Loan for a car, house, or similar.</p>
          <form action="{% url 'mortgage:loan_create'%}" method="GET">
            {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">Create</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">

    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Expense (Interval)</h5>
          <p class="card-text">An expense that occurs at regular intervals, such as a rent, insurance, subscription, or other payment.</p>
          <form action="{% url 'mortgage:expenseinterval_create'%}" method="GET">
            {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">Create</button>
          </form>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Expense (Ad hoc)</h5>
          <p class="card-text">An expense that occurs once for a specific purpose, such as a food or ticket purchase.</p>
          <form action="{% url 'mortgage:expenseadhoc_create'%}" method="GET">
            {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">Create</button>
          </form>
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

smashedavo/backend/templates/mortgage/expenseadhoc_create.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Create New Expense (Ad hoc)</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-success" type="submit">Submit</button>
  </form>

{% endblock content %}

smashedavo/backend/templates/mortgage/expenseinterval_create.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Create New Expense (Interval)</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-success" type="submit">Submit</button>
  </form>

{% endblock content %}

smashedavo/backend/templates/mortgage/expenseinterval_details.html
{% extends 'mortgage/base.html' %}
{% block content %}

  <h1>Expense (Interval) Details</h1>
        
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Amount</th>
        <th scope="col">Category</th>
        <th scope="col">Interval</th>
        <th scope="col">Loan</th>
        <th scope="col">Next Payment Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
      <tr>
        <td>{{expenseinterval.description}}</td>
        <td>{{expenseinterval.amount}}</td>
        <td>{{expenseinterval.category}}</td>
        <td>{{expenseinterval.interval}}</td>
        <td>{{expenseinterval.loan.description}}</td>
        <td>{{expenseinterval.next_payment_date}}</td>
        <td>
          <form action="{% url 'mortgage:expenseinterval_edit' expenseinterval.id %}" method="GET">
            {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">Edit</button>
          </form>
        </td>
      </tr>
  </table>

  <h2>Associated Payments</h2>
  <table class="table table-hover">
    <thead>
        <tr class="table-head">
        <th scope="col">Description</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
        <th scope="col">Approved</th>
      </tr>
    </thead>
      {% for expenseadhoc in expensesadhoc %}
        {% if expenseadhoc.approved %}
          <tr class="table-light">
        {% else %}
          <tr class="table-warning">
        {% endif %}
          <td>{{expenseadhoc.description}}</td>
          <td>{{expenseadhoc.amount}}</td>
          <td>{{expenseadhoc.date}}</td>
          <td>{{expenseadhoc.approved}}</td>
        </tr>
      {% endfor %}
  </table>

{% endblock content %}

smashedavo/backend/templates/mortgage/expenseinterval_edit.html
{% extends 'mortgage/base.html' %}

{% block content %}

  <h1>Update Expense (Interval) Details</h1>

  <form class="form-inline" action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-primary" type="submit">Update</button>
  </form>
  <br>
  <div class="input-group mb-3">
    <form action="{% url 'mortgage:expenseinterval_delete' expenseinterval.id %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-outline-danger" type="submit">Delete</button>
    </form>
  </div>


{% endblock content %}

smashedavo/backend/templates/mortgage/index.html
{% extends 'mortgage/base.html' %}
{% block content %}
    <h1>Welcome to Smashed Avacados</h1>
    <p>TODO</p>
{% endblock content %}

smashedavo/backend/templates/mortgage/loan_detail.html
{% extends 'mortgage/base.html' %}
{% load humanize %}
{% block content %}


    <h1>Loan Details</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Amount Initial</th>
          <th scope="col">Amount Remaining</th>
          <th scope="col">Interest Rate</th>
          <th scope="col">Paid Principal</th>
          <th scope="col">Paid Interest</th>
          <th scope="col">Type</th>
          <th scope="col">Start Date</th>
        </tr>
      </thead>
        <tr>
          <td>{{loan.amount_initial|floatformat:"2"|intcomma}}</td>
          <td>{{loan.amount_remaining|floatformat:"2"|intcomma}}</td>
          <td>{{loan.interest_rate|floatformat:"2"|intcomma}}</td>
          <td>{{loan.paid_principal|floatformat:"2"|intcomma}}</td>
          <td>{{loan.paid_interest|floatformat:"2"|intcomma}}</td>
          <td>{{loan.loan_type}}</td>
          <td>{{loan.start_date}}</td>
        </tr>
    </table>

    <h2>Associated Interval Payments</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Description</th>
          <th scope="col">Amount</th>
          <th scope="col">Category</th>
          <th scope="col">Interval</th>
          <th scope="col">Loan</th>
          <th scope="col">Next Payment Date</th>
          <th scope="col"></th>
        </tr>
      </thead>
        {% for expenseinterval in expensesinterval %}
          <tr>
            <td>{{expenseinterval.description}}</td>
            <td>{{expenseinterval.amount|floatformat:"2"|intcomma}}</td>
            <td>{{expenseinterval.category}}</td>
            <td>{{expenseinterval.interval}}</td>
            <td>{{expenseinterval.loan.description}}</td>
            <td>{{expenseinterval.next_payment_date}}</td>
          </tr>
        {% endfor%}
    </table>
  
  <h2>Associated Individual Payments</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Amount</th>
        <th scope="col">Interest</th>
        <th scope="col">Principal</th>
        <th scope="col">Approved</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
      {% for expenseadhoc in expensesadhoc %}
        <tr>
          <td>{{expenseadhoc.description}}</td>
          <td>{{expenseadhoc.amount|floatformat:"2"|intcomma}}</td>
          <td>{{expenseadhoc.loan_amount_interest|floatformat:"2"|intcomma}}</td>
          <td>{{expenseadhoc.loan_amount_principal|floatformat:"2"|intcomma}}</td>
          <td>{{expenseadhoc.approved}}</td>
          <td>{{expenseadhoc.date}}</td>
        </tr>
      {% endfor %}
  </table>

{% endblock content %}

smashedavo/backend/templates/mortgage/loan_edit.html
{% extends 'mortgage/base.html' %}

{% block headerextra %}
{% endblock headerextra %}

{% block content %}

  <h1>Existing Loan Details</h1>

    <form class="form-inline" action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <br>
      <button class="btn btn-outline-primary" type="submit">Update</button>
    </form>
    <br>
  <div class="input-group mb-3">
    <form action="{% url 'mortgage:loan_delete' loan.id %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-outline-danger" type="submit">Delete</button>
    </form>
    <br>
    <form action="{% url 'mortgage:loan_list' %}" method="GET">
      <button class="btn btn-outline-secondary" type="submit">Back</button>
    </form>
  </div>


{% endblock content %}

smashedavo/backend/templates/mortgage/signup.html
{% extends 'mortgage/base.html' %}
{% block content %}

<h1>Signup</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    {% if failed is not None %}
        <div class="alert alert-danger" role="alert">
            Signup failed: {{failed}}.
        </div>
    {% endif %}
    <button class="btn btn-outline-primary" type="submit">Create Account</button>
</form>

{% endblock content %}